# Book settings
author: Erick Palacios Moreno
title: ""
logo: logo.png

repository:
  url: https://github.com/palmoreck/dockerfiles-for-binder/
  branch: jupyterlab_c_kernel
  path_to_book: analisis-numerico-computo-cientifico
  
launch_buttons:
  notebook_interface: "jupyterlab" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"

latex:
  latex_documents:
    targetname: book.tex
