# Book settings
author: Erick Palacios Moreno
title: ""
logo: logo.png

repository:
  #url: https://github.com/palmoreck/dockerfiles-for-binder/
  #branch:  jupyterlab_opt_c_r_kernel_tidyverse
  url: https://github.com/ITAM-DS/analisis-numerico-computo-cientifico.git
  branch: master
  #path_to_book: libro_optimizacion/temas/

html:
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true

launch_buttons:
  notebook_interface: "jupyterlab" # The interface interactive links will activate ["classic", "jupyterlab"]
  #binderhub_url: "https://mybinder.org"
  binderhub_url: "https://mybinder.org/v2/gh/palmoreck/dockerfiles-for-binder/jupyterlab_opt_c_r_kernel_tidyverse"
  thebe: true

latex:
  latex_documents:
    targetname: book.tex
