# Book settings
author: Erick Palacios Moreno
title: ""
logo: logo.png

repository:
  url: https://github.com/ITAM-DS/analisis-numerico-computo-cientifico/
  branch: master
  path_to_book: libro_optimizacion/temas/

html:
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true

launch_buttons:
  notebook_interface: "jupyterlab" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"
  binder_repo_base: https://github.com/
  binder_repo_org: palmoreck
  binder_repo_name: dockerfiles-for-binder
  binder_repo_branch: jupyterlab_opt_c_r_kernel_tidyverse
  thebe: true

latex:
  latex_documents:
    targetname: book.tex
