# Book settings
author: Erick Palacios Moreno
title: ""
logo: logo.png

repository:
  url: https://github.com/palmoreck/dockerfiles-for-binder/
  branch:  jupyterlab_opt_c_r_kernel_tidyverse
  path_to_book: /home/jovyan/analisis-numerico-computo-cientifico/libro_optimizacion/temas/
  
launch_buttons:
  notebook_interface: "jupyterlab" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"
  thebe: true

latex:
  latex_documents:
    targetname: book.tex
